name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-release

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-release-${{ hashFiles('package-lock.json') }}
      - name: install
        run: |
          npm install
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
